package analizador_componentes;
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class Sym {
  /* terminals */
  public static final int PUNTO = 15;
  public static final int IGUAL = 14;
  public static final int CUERPO = 11;
  public static final int PARENTESIS_ABRE = 16;
  public static final int PARENTESIS_CIERRA = 17;
  public static final int GARRA = 12;
  public static final int INICIAR = 5;
  public static final int EOF = 0;
  public static final int BASE = 10;
  public static final int REPETIR = 9;
  public static final int error = 1;
  public static final int NUMERO = 3;
  public static final int IDENTIFICADOR = 2;
  public static final int PUNTO_COMA = 18;
  public static final int DETENER = 6;
  public static final int CERRAR_GARRA = 7;
  public static final int VELOCIDAD = 13;
  public static final int ROBOT = 4;
  public static final int ABRIR_GARRA = 8;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "DESCONOCIDO",
  "IDENTIFICADOR",
  "NUMERO",
  "ROBOT",
  "INICIAR",
  "DETENER",
  "CERRAR_GARRA",
  "ABRIR_GARRA",
  "REPETIR",
  "BASE",
  "CUERPO",
  "GARRA",
  "VELOCIDAD",
  "IGUAL",
  "PUNTO",
  "PARENTESIS_ABRE",
  "PARENTESIS_CIERRA",
  "PUNTO_COMA"
  };
}

